name: 'AWS Parameter Store Injector'
description: 'Secret management for GitHub Actions using AWS Systems Manager Parameter Store.'
branding:
  icon: briefcase
  color: orange
inputs:
  aws-region:
    required: true
    description: 'The AWS Region to use'
  secrets:
    description: 'Key=Value pairs to push to SSM. Key do not need to have arn.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
